language: node_js
install:
  - npm install
  - cd frontend
  - nvm install node
  - node -v
  - npm i -g yarn
  - npm install jest --global
  - yarn
  - npm i jest-fetch-mock
script:
  - npm run test
  - cd ..
  - 
