language: node_js
node_js:
  - 12.18.3
install:
  - npm install && npm run client-install
  - nvm install node
  - node -v
  - npm i -g yarn
  - npm install jest --global
  - npm i jest-fetch-mock
script:
  - jest
  - cd client
  - npm test
