// auth
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_PICTURE = "UPDATE_PICTURE";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const SET_SOCKET = "SET_SOCKET";
export const UNSET_SOCKET = "UNSET_SOCKET";

// contact
export const GET_SUGGESTION = "GET_SUGGESTION";
export const GET_CONTACTS = "GET_CONTACTS";
export const ADD_CONTACT = "ADD_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const GET_ALL_USERS = "GET_ALL_USERS";

// status
export const GET_STATUS = "GET_STATUS";

// chat
export const CONNECT_SOCKET = "CONNECT_SOCKET";
export const DISCONNECT_SOCKET = "DISCONNECT_SOCKET";
export const JOIN_ROOM = "JOIN_ROOM";
export const LOAD_PAST_MESSAGES = "LOAD_PAST_MESSAGES";
export const RECEIVE_NEW_MESSAGES = "RECEIVE_NEW_MESSAGES";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SET_ITEM_STATUS = "SET_ITEM_STATUS";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const INITIATE_VIDEO_CALL = "INITIATE_VIDEO_CALL";
export const RECEIVE_VIDEO_CALL = "RECEIVE_VIDEO_CALL";
export const PICK_UP_VIDEO_CALL = "PICK_UP_VIDEO_CALL";
export const HANG_UP_VIDEO_CALL = "HANG_UP_VIDEO_CALL";
export const SET_CALLEE_ONLINE = "SET_CALLEE_ONLINE";
export const SET_CALLEE_OFFLINE = "SET_CALLEE_OFFLINE";
export const STOP_WAITING_FOR_CALLEE_RESPONSE = "STOP_WAITING_FOR_CALLEE_RESPONSE";