export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_PICTURE = "UPDATE_PICTURE";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";


